import { PanchayatSettings, Category, Project, ProjectImage, OtherWork, OtherWorkImage, WelfareStat } from './types';

export const sampleSettings: PanchayatSettings = {
    id: '1',
    panchayat_name_hi: 'ग्राम पंचायत सुनहरापुर',
    panchayat_name_en: 'Gram Panchayat Sunahrapur',
    block_hi: 'सदर',
    block_en: 'Sadar',
    district_hi: 'रायपुर',
    district_en: 'Raipur',
    state_hi: 'छत्तीसगढ़',
    state_en: 'Chhattisgarh',
    representative_name_hi: 'श्रीमती सीता देवी पटेल',
    representative_name_en: 'Smt. Sita Devi Patel',
    representative_photo_url: null,
    spouse_name_hi: 'श्री रामप्रसाद पटेल',
    spouse_name_en: 'Shri Ramprasad Patel',
    spouse_photo_url: null,
    village_photo_url: null,
    tenure_start: 2020,
    tenure_end: 2025,
    election_slogan_hi: null,
    election_slogan_en: null,
    election_year: null,
    election_symbol: null,
    campaign_message_hi: null,
    campaign_message_en: null,
    promises: [],
    show_campaign: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
};

export const sampleCategories: Category[] = [
    { id: 'cat-1', name_hi: 'सड़क एवं नाली', name_en: 'Roads & Drains', icon: '🛣️', sort_order: 1, created_at: new Date().toISOString() },
    { id: 'cat-2', name_hi: 'पेयजल', name_en: 'Drinking Water', icon: '💧', sort_order: 2, created_at: new Date().toISOString() },
    { id: 'cat-3', name_hi: 'प्रकाश व्यवस्था', name_en: 'Street Lighting', icon: '💡', sort_order: 3, created_at: new Date().toISOString() },
    { id: 'cat-4', name_hi: 'शिक्षा', name_en: 'Education', icon: '🏫', sort_order: 4, created_at: new Date().toISOString() },
    { id: 'cat-5', name_hi: 'स्वच्छता', name_en: 'Cleanliness', icon: '🧹', sort_order: 5, created_at: new Date().toISOString() },
    { id: 'cat-6', name_hi: 'सामुदायिक विकास', name_en: 'Community Development', icon: '🏘️', sort_order: 6, created_at: new Date().toISOString() },
    { id: 'cat-7', name_hi: 'पर्यावरण', name_en: 'Environment', icon: '🌳', sort_order: 7, created_at: new Date().toISOString() },
    { id: 'cat-8', name_hi: 'अन्य', name_en: 'Others', icon: '⚡', sort_order: 8, created_at: new Date().toISOString() },
];

const makeImages = (projectId: string, seed: number): ProjectImage[] => [
    {
        id: `img-${projectId}-b`,
        project_id: projectId,
        image_url: `https://placehold.co/800x600/e2e8f0/475569?text=Before+${seed}`,
        image_type: 'before',
        caption: null,
        sort_order: 0,
        is_primary: true,
        ai_suggested_type: null,
        created_at: new Date().toISOString(),
    },
    {
        id: `img-${projectId}-a`,
        project_id: projectId,
        image_url: `https://placehold.co/800x600/dcfce7/166534?text=After+${seed}`,
        image_type: 'after',
        caption: null,
        sort_order: 1,
        is_primary: true,
        ai_suggested_type: null,
        created_at: new Date().toISOString(),
    },
];

export const sampleProjects: Project[] = [
    {
        id: 'p-1', title_hi: 'मुख्य मार्ग एवं नाली निर्माण', title_en: 'Main Road & Drain Construction',
        description_hi: 'ग्राम के मुख्य मार्ग का सीमेंट कंक्रीट से निर्माण तथा दोनों ओर पक्की नाली का निर्माण किया गया। इससे बरसात में जलभराव की समस्या समाप्त हुई।',
        description_en: 'Cement concrete construction of the main village road with paved drains on both sides, eliminating waterlogging during rains.',
        category_id: 'cat-1', ward: 'वार्ड 4', location_hi: 'मुख्य मार्ग', location_en: 'Main Road',
        completion_year: 2023, completion_date: '2023-06-15', cost_lakhs: 12.5,
        scheme: 'MGNREGA', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: true,
        slug: 'main-road-drain-construction', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-1', 1),
    },
    {
        id: 'p-2', title_hi: 'हैंडपंप एवं जल टंकी स्थापना', title_en: 'Handpump & Water Tank Installation',
        description_hi: 'पेयजल की समस्या को दूर करने के लिए 3 नए हैंडपंप एवं 1 ऊँची जल टंकी की स्थापना की गई।',
        description_en: 'Installation of 3 new handpumps and 1 elevated water tank to resolve drinking water issues.',
        category_id: 'cat-2', ward: 'वार्ड 2', location_hi: 'चौक के पास', location_en: 'Near Chowk',
        completion_year: 2022, completion_date: '2022-11-20', cost_lakhs: 8.0,
        scheme: 'जल जीवन मिशन', department: 'लोक स्वास्थ्य यांत्रिकी', status: 'published', is_featured: true,
        slug: 'handpump-water-tank', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-2', 2),
    },
    {
        id: 'p-3', title_hi: 'सोलर स्ट्रीट लाइट लगाना', title_en: 'Solar Street Light Installation',
        description_hi: 'गाँव की प्रमुख गलियों एवं चौराहों पर 25 सोलर स्ट्रीट लाइट लगाई गई जिससे रात में रोशनी की व्यवस्था हुई।',
        description_en: '25 solar street lights installed on main lanes and intersections for nighttime illumination.',
        category_id: 'cat-3', ward: 'वार्ड 1, 3, 5', location_hi: 'विभिन्न गलियाँ', location_en: 'Various Lanes',
        completion_year: 2023, completion_date: '2023-03-10', cost_lakhs: 6.75,
        scheme: 'सांसद आदर्श ग्राम योजना', department: 'ऊर्जा विभाग', status: 'published', is_featured: true,
        slug: 'solar-street-lights', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-3', 3),
    },
    {
        id: 'p-4', title_hi: 'प्राथमिक विद्यालय मरम्मत', title_en: 'Primary School Renovation',
        description_hi: 'शासकीय प्राथमिक विद्यालय की छत की मरम्मत, दीवारों की पुताई, फर्श निर्माण एवं शौचालय निर्माण किया गया।',
        description_en: 'Renovation of government primary school including roof repair, wall painting, floor construction and toilet construction.',
        category_id: 'cat-4', ward: 'वार्ड 3', location_hi: 'विद्यालय परिसर', location_en: 'School Campus',
        completion_year: 2022, completion_date: '2022-07-25', cost_lakhs: 4.5,
        scheme: 'समग्र शिक्षा अभियान', department: 'शिक्षा विभाग', status: 'published', is_featured: false,
        slug: 'primary-school-renovation', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-4', 4),
    },
    {
        id: 'p-5', title_hi: 'सामुदायिक शौचालय निर्माण', title_en: 'Community Toilet Construction',
        description_hi: 'खुले में शौच मुक्त (ODF) अभियान के तहत 2 सामुदायिक शौचालय का निर्माण किया गया।',
        description_en: '2 community toilets constructed under ODF (Open Defecation Free) campaign.',
        category_id: 'cat-5', ward: 'वार्ड 1', location_hi: 'बस स्टैंड के पास', location_en: 'Near Bus Stand',
        completion_year: 2021, completion_date: '2021-10-02', cost_lakhs: 3.0,
        scheme: 'स्वच्छ भारत मिशन', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: false,
        slug: 'community-toilet', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-5', 5),
    },
    {
        id: 'p-6', title_hi: 'सामुदायिक भवन निर्माण', title_en: 'Community Hall Construction',
        description_hi: 'ग्राम में सभाओं, विवाह समारोहों एवं सामूहिक कार्यक्रमों के लिए एक सामुदायिक भवन का निर्माण किया गया।',
        description_en: 'Construction of a community hall for village meetings, weddings and community events.',
        category_id: 'cat-6', ward: 'वार्ड 2', location_hi: 'ग्राम पंचायत भवन', location_en: 'Village Panchayat Bhawan',
        completion_year: 2024, completion_date: '2024-01-26', cost_lakhs: 18.0,
        scheme: 'MGNREGA', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: true,
        slug: 'community-hall', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-6', 6),
    },
    {
        id: 'p-7', title_hi: 'गली नाली पक्कीकरण - वार्ड 5', title_en: 'Lane Drain Construction - Ward 5',
        description_hi: 'वार्ड 5 की सभी गलियों में पक्की नाली का निर्माण कराया गया जिससे गंदे पानी की निकासी सुचारू हुई।',
        description_en: 'Construction of paved drains in all lanes of Ward 5 for proper sewage drainage.',
        category_id: 'cat-1', ward: 'वार्ड 5', location_hi: 'समस्त गलियाँ', location_en: 'All Lanes',
        completion_year: 2024, completion_date: '2024-05-15', cost_lakhs: 7.25,
        scheme: 'पंचायत निधि', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: false,
        slug: 'lane-drain-ward-5', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-7', 7),
    },
    {
        id: 'p-8', title_hi: 'आंगनबाड़ी केंद्र निर्माण', title_en: 'Anganwadi Center Construction',
        description_hi: 'बच्चों के पोषण एवं प्रारंभिक शिक्षा के लिए नवीन आंगनबाड़ी केंद्र का निर्माण किया गया।',
        description_en: 'New Anganwadi center constructed for child nutrition and early education.',
        category_id: 'cat-4', ward: 'वार्ड 6', location_hi: 'पटेल मोहल्ला', location_en: 'Patel Mohalla',
        completion_year: 2023, completion_date: '2023-08-15', cost_lakhs: 5.0,
        scheme: 'ICDS', department: 'महिला एवं बाल विकास', status: 'published', is_featured: false,
        slug: 'anganwadi-center', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-8', 8),
    },
    {
        id: 'p-9', title_hi: 'तालाब गहरीकरण एवं सौंदर्यीकरण', title_en: 'Pond Deepening & Beautification',
        description_hi: 'ग्राम के मुख्य तालाब का गहरीकरण कर चारों ओर पक्की पाल एवं सीढ़ियाँ बनाई गई।',
        description_en: 'Deepening of the main village pond with paved embankment and steps constructed around it.',
        category_id: 'cat-7', ward: 'वार्ड 3', location_hi: 'मुख्य तालाब', location_en: 'Main Pond',
        completion_year: 2022, completion_date: '2022-04-22', cost_lakhs: 9.0,
        scheme: 'MGNREGA', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: true,
        slug: 'pond-beautification', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-9', 9),
    },
    {
        id: 'p-10', title_hi: 'पेयजल पाइपलाइन बिछाना', title_en: 'Drinking Water Pipeline Installation',
        description_hi: 'नल-जल योजना के तहत 2 किमी पाइपलाइन बिछाकर 150 घरों तक पेयजल पहुँचाया गया।',
        description_en: 'Under Nal-Jal scheme, 2km pipeline laid to provide drinking water to 150 households.',
        category_id: 'cat-2', ward: 'वार्ड 4, 6', location_hi: 'विभिन्न मोहल्ले', location_en: 'Various Localities',
        completion_year: 2024, completion_date: '2024-03-20', cost_lakhs: 15.0,
        scheme: 'जल जीवन मिशन', department: 'लोक स्वास्थ्य यांत्रिकी', status: 'published', is_featured: false,
        slug: 'water-pipeline', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-10', 10),
    },
    {
        id: 'p-11', title_hi: 'सीसी रोड निर्माण - वार्ड 2', title_en: 'CC Road Construction - Ward 2',
        description_hi: 'वार्ड 2 में 500 मीटर सीमेंट कंक्रीट सड़क का निर्माण कराया गया।',
        description_en: '500 meter cement concrete road constructed in Ward 2.',
        category_id: 'cat-1', ward: 'वार्ड 2', location_hi: 'यादव मोहल्ला', location_en: 'Yadav Mohalla',
        completion_year: 2023, completion_date: '2023-12-10', cost_lakhs: 8.5,
        scheme: 'PMGSY', department: 'लोक निर्माण विभाग', status: 'published', is_featured: false,
        slug: 'cc-road-ward-2', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-11', 11),
    },
    {
        id: 'p-12', title_hi: 'कूड़ा प्रबंधन एवं डस्टबिन स्थापना', title_en: 'Waste Management & Dustbin Installation',
        description_hi: 'ग्राम में 30 डस्टबिन लगाए गए तथा कूड़ा एकत्रण वाहन की व्यवस्था की गई।',
        description_en: '30 dustbins installed in the village with waste collection vehicle arrangement.',
        category_id: 'cat-5', ward: 'सभी वार्ड', location_hi: 'सम्पूर्ण ग्राम', location_en: 'Entire Village',
        completion_year: 2024, completion_date: '2024-06-05', cost_lakhs: 2.5,
        scheme: 'स्वच्छ भारत मिशन', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: false,
        slug: 'waste-management', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-12', 12),
    },
    {
        id: 'p-13', title_hi: 'LED स्ट्रीट लाइट - वार्ड 6', title_en: 'LED Street Lights - Ward 6',
        description_hi: 'वार्ड 6 में 15 LED स्ट्रीट लाइट लगाई गई।',
        description_en: '15 LED street lights installed in Ward 6.',
        category_id: 'cat-3', ward: 'वार्ड 6', location_hi: 'मुख्य गलियाँ', location_en: 'Main Lanes',
        completion_year: 2024, completion_date: '2024-02-14', cost_lakhs: 3.25,
        scheme: 'पंचायत निधि', department: 'ऊर्जा विभाग', status: 'published', is_featured: false,
        slug: 'led-lights-ward-6', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-13', 13),
    },
    {
        id: 'p-14', title_hi: 'सीसी रोड - मंदिर मार्ग', title_en: 'CC Road - Temple Road',
        description_hi: 'मंदिर तक जाने वाले मार्ग का सीमेंट कंक्रीट से पक्कीकरण किया गया।',
        description_en: 'Cement concrete construction of the road leading to the temple.',
        category_id: 'cat-1', ward: 'वार्ड 1', location_hi: 'मंदिर मार्ग', location_en: 'Temple Road',
        completion_year: 2021, completion_date: '2021-12-25', cost_lakhs: 5.0,
        scheme: 'MGNREGA', department: 'पंचायत एवं ग्रामीण विकास', status: 'published', is_featured: false,
        slug: 'cc-road-temple', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-14', 14),
    },
    {
        id: 'p-15', title_hi: 'खेल मैदान विकास', title_en: 'Playground Development',
        description_hi: 'बच्चों के लिए खेल मैदान का समतलीकरण एवं खेल सामग्री की स्थापना की गई।',
        description_en: 'Leveling of playground and installation of sports equipment for children.',
        category_id: 'cat-6', ward: 'वार्ड 3', location_hi: 'विद्यालय के पास', location_en: 'Near School',
        completion_year: 2025, completion_date: '2025-01-26', cost_lakhs: 4.0,
        scheme: 'खेलो इंडिया', department: 'खेल एवं युवा कल्याण', status: 'published', is_featured: false,
        slug: 'playground-development', created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: makeImages('p-15', 15),
    },
];

export const sampleOtherWorks: OtherWork[] = [
    {
        id: 'ow-1', title_hi: 'वृक्षारोपण अभियान', title_en: 'Tree Plantation Drive',
        description_hi: 'पर्यावरण दिवस पर 500 पौधों का रोपण किया गया।',
        description_en: '500 saplings planted on Environment Day.',
        category: 'पर्यावरण', location_hi: 'सम्पूर्ण ग्राम', location_en: 'Entire Village',
        event_date: '2023-06-05', event_year: 2023, status: 'published',
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: [{ id: 'owi-1', other_work_id: 'ow-1', image_url: 'https://placehold.co/600x400/d1fae5/065f46?text=Plantation', caption: null, sort_order: 0, created_at: new Date().toISOString() }],
    },
    {
        id: 'ow-2', title_hi: 'स्वच्छता रैली', title_en: 'Cleanliness Rally',
        description_hi: 'ग्रामीणों ने मिलकर स्वच्छता रैली निकाली एवं गाँव की सफाई की।',
        description_en: 'Villagers organized a cleanliness rally and cleaned the village.',
        category: 'स्वच्छता', location_hi: 'सम्पूर्ण ग्राम', location_en: 'Entire Village',
        event_date: '2024-10-02', event_year: 2024, status: 'published',
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: [{ id: 'owi-2', other_work_id: 'ow-2', image_url: 'https://placehold.co/600x400/fef3c7/92400e?text=Rally', caption: null, sort_order: 0, created_at: new Date().toISOString() }],
    },
    {
        id: 'ow-3', title_hi: 'स्वास्थ्य शिविर', title_en: 'Health Camp',
        description_hi: 'निःशुल्क स्वास्थ्य जाँच शिविर का आयोजन किया गया जिसमें 200 ग्रामीणों ने लाभ उठाया।',
        description_en: 'Free health check-up camp organized benefiting 200 villagers.',
        category: 'स्वास्थ्य', location_hi: 'सामुदायिक भवन', location_en: 'Community Hall',
        event_date: '2024-04-07', event_year: 2024, status: 'published',
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: [{ id: 'owi-3', other_work_id: 'ow-3', image_url: 'https://placehold.co/600x400/ede9fe/5b21b6?text=Health+Camp', caption: null, sort_order: 0, created_at: new Date().toISOString() }],
    },
    {
        id: 'ow-4', title_hi: 'खेलकूद प्रतियोगिता', title_en: 'Sports Competition',
        description_hi: 'गणतंत्र दिवस पर ग्रामीण खेलकूद प्रतियोगिता का आयोजन हुआ।',
        description_en: 'Rural sports competition organized on Republic Day.',
        category: 'खेलकूद', location_hi: 'खेल मैदान', location_en: 'Playground',
        event_date: '2025-01-26', event_year: 2025, status: 'published',
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: [{ id: 'owi-4', other_work_id: 'ow-4', image_url: 'https://placehold.co/600x400/dbeafe/1e40af?text=Sports', caption: null, sort_order: 0, created_at: new Date().toISOString() }],
    },
    {
        id: 'ow-5', title_hi: 'ग्राम सभा एवं जन संवाद', title_en: 'Gram Sabha & Public Dialogue',
        description_hi: 'ग्राम विकास की योजना बनाने हेतु विशेष ग्राम सभा एवं जन संवाद का आयोजन।',
        description_en: 'Special Gram Sabha and public dialogue organized for village development planning.',
        category: 'शासन', location_hi: 'पंचायत भवन', location_en: 'Panchayat Bhawan',
        event_date: '2023-08-15', event_year: 2023, status: 'published',
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        images: [{ id: 'owi-5', other_work_id: 'ow-5', image_url: 'https://placehold.co/600x400/fce7f3/9d174d?text=Gram+Sabha', caption: null, sort_order: 0, created_at: new Date().toISOString() }],
    },
];

export const sampleWelfareStats: WelfareStat[] = [
    { id: 'ws-1', label_hi: 'आवास वितरण', label_en: 'Housing Distributed', icon: '🏠', count: 85, unit_hi: 'आवास', unit_en: 'Houses', sort_order: 1 },
    { id: 'ws-2', label_hi: 'शौचालय निर्माण', label_en: 'Toilets Built', icon: '🚽', count: 120, unit_hi: 'शौचालय', unit_en: 'Toilets', sort_order: 2 },
    { id: 'ws-3', label_hi: 'पेंशन लाभार्थी', label_en: 'Pension Beneficiaries', icon: '👴', count: 65, unit_hi: 'लाभार्थी', unit_en: 'Beneficiaries', sort_order: 3 },
    { id: 'ws-4', label_hi: 'सड़क निर्माण', label_en: 'Roads Completed', icon: '🛣️', count: 12, unit_hi: 'सड़कें', unit_en: 'Roads', sort_order: 4 },
    { id: 'ws-5', label_hi: 'नल-जल कनेक्शन', label_en: 'Tap Water Connections', icon: '💧', count: 150, unit_hi: 'कनेक्शन', unit_en: 'Connections', sort_order: 5 },
    { id: 'ws-6', label_hi: 'राशन कार्ड', label_en: 'Ration Cards', icon: '🪪', count: 210, unit_hi: 'कार्ड', unit_en: 'Cards', sort_order: 6 },
];
